services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    volumes:
      - pg-data:/var/lib/postgresql/data/pgdata
    networks:
      - app
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB_NAME}
      PGDATA: "/var/lib/postgresql/data/pgdata"

  adminer:
    image: adminer
    restart: always
    networks:
      - app
    ports:
      - 6144:8080

networks:
  app:
    driver: bridge

volumes:
  pg-data: