version: '3.8'

services:
  db:
    image: postgres
    restart: always
    shm_size: 512mb
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"

  adminer:
    image: adminer
    restart: always
    networks:
      - app
    ports:
      - "6144:8080"

networks:
  app:
    driver: bridge
